name: Clone Repo To Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy Repository to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |

            echo "Connected to Server"

            cd /tmp

            if [ -d "newproject" ]; then
              echo "Repository Exists"
              cd newproject
              git pull
            else
              echo "Cloning Repository"
              git clone https://github.com/Kavin-dev54/serverdeploy.git
            fi

            echo "Deployment Completed"

            ls -la /tmp

            cd /tmp/newproject

            ls -lahttps://github.com/Kavin-dev54/serverdeploy.git
