name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -tt -i ~/.ssh/id_ed25519 root@${{ secrets.HOST }} << 'EOF'

            set -x

            echo "CONNECTED"

            echo "CURRENT USER:"
            whoami

            echo "CURRENT PATH:"
            pwd

            echo "CHECKING DIRECTORY"

            if [ ! -d "/tmp/serverdeploy" ]; then
              echo "DIRECTORY NOT FOUND"
              exit 1
            fi

            cd /tmp/serverdeploy

            echo "INSIDE DIRECTORY"
            pwd

            echo "FILES:"
            ls -la

            echo "GIT STATUS:"
            git status

            echo "PULLING CODE"
            git pull origin main

            echo "DEPLOY SUCCESS"

          EOF
